sdbusplus: add config.h header for constant
clang-tidy fails with the following warning:

```
/var/jenkins-openbmc/workspace/ci-repository/openbmc/phosphor-nvme/sdbusplus.hpp:34:51: error: use of undeclared identifier 'DBUS_PROPERTY_IFACE' [clang-diagnostic-error]
   34 |                 busName.c_str(), objPath.c_str(), DBUS_PROPERTY_IFACE, "Set");
```

Add the missing `config.h` header where this is defined.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ic96f71dbd37d5c25d158f77321f26371b51198cf